### ISSUE TITLE
permission issue. 

### ISSUE THREAD

**Issue by mattman73** [jwdempsey/PlexTools.bundle#16]
I have install PlexTools and it is working in the web ui but when I try to convert a video file it is not working I do believe that it might have something to do with the permission on the files, I have tried to set the files as root and apache but this is not working also I have set them for read / write for groups, user, others. 
But I still can not get it to convert the files to mp4.
Thanks
Regards
MattMan

**Comment by jwdempsey** [comment]
You will need to post your log files so that I can take a look. I will say that permission issues aren't something I am going to provide much help with as its outside the scope of the plugin.

**Comment by mattman73** [comment]
Hi
Please find a log file here i'm not sure if it is a permission issues so please could you have a look.
Regards
MattMan
http://ur1.ca/jm405

**Comment by jwdempsey** [comment]
I took a log at your logs and I noticed this error:
`[Unknown ffmpeg error Could not write header for output file #0 (incorrect codec parameters ?): No space left on device]`

Based on that error I'm guessing it's one of two things. You either don't enough free space on your hard drive to convert the file or ffmpeg couldn't make an accurate guess as to what type of codec your file is.
