### ISSUE TITLE
Plex Tools won't repond. 

### ISSUE THREAD

**Issue by arndan** [jwdempsey/PlexTools.bundle#21]
When i go on Plex Tools i meet this "This channel is not responding". Picture here https://i.imgur.com/gpHKtY8.png

**Comment by AreFinstad** [comment]
this is still an issue, here is some logs that covers server boot and trying to enter the main plugin window.
https://drive.google.com/file/d/0B-hww4iUE6HsdFE3dWN3aEd1c2M/view?usp=sharing

hope you can look into this soon, as the plugin does not work at all for me at this point.
using this same issue that already was here as its the same problem.

its getting an error when trying to open: http://localhost:32400/library/sections/
also getting a 401error when opening that page itself.... ofc that isnt a page that we should be using tho.

also to note that my OpenSubs, FFMPEG, FFPROBE settings are all filled out and the rest is vanilla settings.

**Comment by jwdempsey** [comment]
@AreFinstad It looks like you are missing your Plex username and password. Please go into the settings for the channel and enter those in. Let me know if you are still having trouble.

**Comment by jwdempsey** [comment]
@arndan I'm sorry but you have to post logs before I can help you.

**Comment by AreFinstad** [comment]
ahhh silly me, thought it was pointing to the myplex site and that said it wasnt in my country XD well thanks for the clear up, its working now. yay! :D

**Comment by jwdempsey** [comment]
@AreFinstad Thanks for the update. I'm glad its working now.

**Comment by AreFinstad** [comment]
while you are around, question:
if i leave the video bitrate empty, will it be the same as the source then?  (im guessing it will)
